name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: MagOss27
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit Changes
        run: |
          git config --global user.email "MagnusOss98@example.com"
          git config --global user.name "MagOss27"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation" || echo "No changes to commit"
