name: Gerar Dados

on:
  schedule: # executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Tarefas para atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Animação da Cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MagOss27
          svg_out_path: .github/workflows/dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: .github/workflows/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
