name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch: 
  push:
    branches:
      - master 

jobs:
  generate:
    permissions:
      contents: write  
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MagOss27 
          outputs: dist/snake.svg?palette=github-dark  

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output 
          build_dir: dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
